services:
  app:
    image: localstack/localstack:latest
    container_name: localstack
    restart: unless-stopped
    ports:
      - "${PORT:-4566}:4566"
    environment:
      - SERVICES=${{SERVICES}}
      - DEBUG=${{DEBUG}}
      - DOCKER_HOST=${{DOCKER_HOST}}
    volumes:
      - app_data:/data
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
  app_data:
